Repository maidsafe/safe_app_java, pull requests merged in 2019-03, with the labels that each got.

#84 test/ClientActions : improve client actions tests
  CHANGELOG.md
  config/log.toml
  config/safe_core.config
  safe-app-android/src/androidTest/java/net/maidsafe/test/utils/Helper.java
  safe-app-android/src/main/assets/log.toml
  safe-app-android/src/main/assets/safe_core.config
  safe-app/src/test/java/net/maidsafe/api/ClientActions.java
  safe-app/src/test/java/net/maidsafe/api/ClientTest.java
  safe-app/src/test/java/net/maidsafe/api/DefaultContainers.java
  safe-app/src/test/java/net/maidsafe/api/MutableDataOperations.java
  safe-app/src/test/java/net/maidsafe/api/TestHelper.java
  safe-app/src/test/java/net/maidsafe/test/utils/Helper.java
Labels: enhancement, p/major

#86 Add artifacts to Appveyor
  appveyor.yml
  build.gradle
Labels: enhancement, p/major

#87 chore/iData: deprecate getSerialisedSize
  CHANGELOG.md
  api/src/main/java/net/maidsafe/api/IData.java
Labels: p/minor

#89 feat/safe-app: use flavours plugin for the safe-app module
  .gitignore
  safe-app-android/build.gradle
  safe-app/.gitignore
  safe-app/build.gradle
  safe-app/src/mock/java/net/maidsafe/api/Authenticator.java
  safe-authenticator/.gitignore
  safe-authenticator/build.gradle
  settings.gradle
Labels: enhancement, p/minor
